#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Oct 13, 2021 04:00:32 PM +0100  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 755x665+444+112
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background #ffffff -height 665 \
        -width 265 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab47 \
        -background #f5010a -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground #ffffff -text Login 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 94 
    vTcl:DefineAlias "$site_3_0.ent48" "user_box" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$site_3_0.ent49" "email_box" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #008040 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Login 
    vTcl:DefineAlias "$site_3_0.but50" "login_btn" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -background #ff0000 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground #ffffff -text Register 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$site_3_0.ent52" "user_reg_box" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$site_3_0.ent53" "email_reg_box" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$site_3_0.ent54" "name_reg_box" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$site_3_0.ent55" "phone_reg_box" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -text Username 
    vTcl:DefineAlias "$site_3_0.lab56" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -text {Email Address} 
    vTcl:DefineAlias "$site_3_0.lab59" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -text {Full Name} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -text {Phone Number} 
    vTcl:DefineAlias "$site_3_0.lab61" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #800040 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Register 
    vTcl:DefineAlias "$site_3_0.but62" "register_btn" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab76 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -text Username 
    vTcl:DefineAlias "$site_3_0.lab76" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab77 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -text {Email Address} 
    vTcl:DefineAlias "$site_3_0.lab77" "Label10" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.996 -height 0 \
        -relheight 0.047 -anchor nw -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.105 -width 194 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.226 -width 194 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.301 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -y 0 -rely 0.391 -width 0 -relwidth 0.996 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.496 -width 194 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent53 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.589 -width 194 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.684 -width 194 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.789 -width 194 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.451 -width 0 \
        -relwidth 0.279 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -rely 0.556 -width 0 \
        -relwidth 0.355 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.647 -width 0 \
        -relwidth 0.317 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -rely 0.737 -width 0 \
        -relwidth 0.392 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 0 -relx 0.189 -y 0 -rely 0.887 -width 147 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.06 -width 0 \
        -relwidth 0.242 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.18 -width 0 \
        -relwidth 0.302 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background #ffffff -height 665 \
        -width 486 
    vTcl:DefineAlias "$top.fra46" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab63 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -text Label 
    vTcl:DefineAlias "$site_3_0.lab63" "user_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab64" "email_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab65" "name_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab66" "phone_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab67" "date_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -text Username 
    vTcl:DefineAlias "$site_3_0.lab68" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Email Address} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label8_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Full Name} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label8_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Phone Number} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label8_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Date Register} 
    vTcl:DefineAlias "$site_3_0.lab74" "Label8_4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Log Out} 
    vTcl:DefineAlias "$site_3_0.but75" "log_out_btn" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.062 -y 0 -rely 0.06 -width 0 \
        -relwidth 0.871 -height 0 -relheight 0.077 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.062 -y 0 -rely 0.256 -width 0 \
        -relwidth 0.871 -height 0 -relheight 0.077 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.062 -y 0 -rely 0.466 -width 0 \
        -relwidth 0.871 -height 0 -relheight 0.077 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.062 -y 0 -rely 0.662 -width 0 \
        -relwidth 0.871 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.062 -y 0 -rely 0.827 -width 0 \
        -relwidth 0.871 -height 0 -relheight 0.077 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.329 -y 0 -rely 0.015 -width 0 \
        -relwidth 0.316 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.329 -y 0 -rely 0.195 -width 0 \
        -relwidth 0.316 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.329 -y 0 -rely 0.406 -width 0 \
        -relwidth 0.316 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.337 -y 0 -rely 0.603 -width 0 \
        -relwidth 0.316 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 0 -relx 0.349 -y 0 -rely 0.767 -width 0 \
        -relwidth 0.316 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but75 \
        -in $site_3_0 -x 0 -relx 0.349 -y 0 -rely 0.932 -width 137 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -relx 0.001 -y 0 -width 0 -relwidth 0.351 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -relx 0.355 -y 0 -width 0 -relwidth 0.645 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

