#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Oct 13, 2021 04:00:23 PM +0100  platform: Windows NT

from os import name
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

import database as db

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import class_python_project_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    class_python_project_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    class_python_project_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("755x665+444+112")
        top.minsize(120, 1)
        top.maxsize(1604, 881)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.001, rely=0.0, relheight=1.0, relwidth=0.351)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#ffffff")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.0, rely=0.0, height=31, width=264)
        self.Label1.configure(background="#f5010a")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Login''')

        self.user_box = tk.Entry(self.Frame1)
        self.user_box.place(relx=0.075, rely=0.105, height=30, relwidth=0.732)
        self.user_box.configure(background="white")
        self.user_box.configure(disabledforeground="#a3a3a3")
        self.user_box.configure(font="TkFixedFont")
        self.user_box.configure(foreground="#000000")
        self.user_box.configure(insertbackground="black")

        self.email_box = tk.Entry(self.Frame1)
        self.email_box.place(relx=0.075, rely=0.226, height=30, relwidth=0.732)
        self.email_box.configure(background="white")
        self.email_box.configure(disabledforeground="#a3a3a3")
        self.email_box.configure(font="TkFixedFont")
        self.email_box.configure(foreground="#000000")
        self.email_box.configure(insertbackground="black")

        self.login_btn = tk.Button(self.Frame1)
        self.login_btn.place(relx=0.264, rely=0.301, height=34, width=97)
        self.login_btn.configure(activebackground="#ececec")
        self.login_btn.configure(activeforeground="#000000")
        self.login_btn.configure(background="#008040")
        self.login_btn.configure(disabledforeground="#a3a3a3")
        self.login_btn.configure(foreground="#ffffff")
        self.login_btn.configure(highlightbackground="#d9d9d9")
        self.login_btn.configure(highlightcolor="black")
        self.login_btn.configure(pady="0")
        self.login_btn.configure(text='''Login''')
        self.login_btn.configure(command= lambda: db.retrievData(
            email= self.user_box.get(),
            username= self.user_box.get()
        ))

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.0, rely=0.391, height=31, width=264)
        self.Label2.configure(background="#ff0000")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 12")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''Register''')

        self.user_reg_box = tk.Entry(self.Frame1)
        self.user_reg_box.place(relx=0.075, rely=0.496, height=30
                , relwidth=0.732)
        self.user_reg_box.configure(background="white")
        self.user_reg_box.configure(disabledforeground="#a3a3a3")
        self.user_reg_box.configure(font="TkFixedFont")
        self.user_reg_box.configure(foreground="#000000")
        self.user_reg_box.configure(insertbackground="black")

        self.email_reg_box = tk.Entry(self.Frame1)
        self.email_reg_box.place(relx=0.075, rely=0.589, height=30
                , relwidth=0.732)
        self.email_reg_box.configure(background="white")
        self.email_reg_box.configure(disabledforeground="#a3a3a3")
        self.email_reg_box.configure(font="TkFixedFont")
        self.email_reg_box.configure(foreground="#000000")
        self.email_reg_box.configure(highlightbackground="#d9d9d9")
        self.email_reg_box.configure(highlightcolor="black")
        self.email_reg_box.configure(insertbackground="black")
        self.email_reg_box.configure(selectbackground="blue")
        self.email_reg_box.configure(selectforeground="white")

        self.name_reg_box = tk.Entry(self.Frame1)
        self.name_reg_box.place(relx=0.075, rely=0.684, height=30
                , relwidth=0.732)
        self.name_reg_box.configure(background="white")
        self.name_reg_box.configure(disabledforeground="#a3a3a3")
        self.name_reg_box.configure(font="TkFixedFont")
        self.name_reg_box.configure(foreground="#000000")
        self.name_reg_box.configure(highlightbackground="#d9d9d9")
        self.name_reg_box.configure(highlightcolor="black")
        self.name_reg_box.configure(insertbackground="black")
        self.name_reg_box.configure(selectbackground="blue")
        self.name_reg_box.configure(selectforeground="white")

        self.phone_reg_box = tk.Entry(self.Frame1)
        self.phone_reg_box.place(relx=0.075, rely=0.789, height=30
                , relwidth=0.732)
        self.phone_reg_box.configure(background="white")
        self.phone_reg_box.configure(disabledforeground="#a3a3a3")
        self.phone_reg_box.configure(font="TkFixedFont")
        self.phone_reg_box.configure(foreground="#000000")
        self.phone_reg_box.configure(highlightbackground="#d9d9d9")
        self.phone_reg_box.configure(highlightcolor="black")
        self.phone_reg_box.configure(insertbackground="black")
        self.phone_reg_box.configure(selectbackground="blue")
        self.phone_reg_box.configure(selectforeground="white")

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.049, rely=0.451, height=21, width=74)
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Username''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.038, rely=0.556, height=21, width=94)
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Email Address''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.023, rely=0.647, height=22, width=84)
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Full Name''')

        self.Label6 = tk.Label(self.Frame1)
        self.Label6.place(relx=0.038, rely=0.737, height=31, width=104)
        self.Label6.configure(background="#ffffff")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Phone Number''')

        self.register_btn = tk.Button(self.Frame1)
        self.register_btn.place(relx=0.189, rely=0.887, height=34, width=147)
        self.register_btn.configure(activebackground="#ececec")
        self.register_btn.configure(activeforeground="#000000")
        self.register_btn.configure(background="#800040")
        self.register_btn.configure(disabledforeground="#a3a3a3")
        self.register_btn.configure(foreground="#ffffff")
        self.register_btn.configure(highlightbackground="#d9d9d9")
        self.register_btn.configure(highlightcolor="black")
        self.register_btn.configure(pady="0")
        self.register_btn.configure(text='''Register''')
        self.register_btn.configure(command= lambda: db.insertData(
            name= self.name_reg_box.get(),
            email= self.email_reg_box.get(),
            phone= self.phone_reg_box.get(),
            username= self.user_reg_box.get()
        ))

        self.Label9 = tk.Label(self.Frame1)
        self.Label9.place(relx=0.075, rely=0.06, height=21, width=64)
        self.Label9.configure(background="#ffffff")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Username''')

        self.Label10 = tk.Label(self.Frame1)
        self.Label10.place(relx=0.075, rely=0.18, height=21, width=80)
        self.Label10.configure(background="#ffffff")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''Email Address''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.355, rely=0.0, relheight=1.0, relwidth=0.645)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#ffffff")

        self.user_label = tk.Label(self.Frame2)
        self.user_label.place(relx=0.062, rely=0.06, height=51, width=424)
        self.user_label.configure(background="#d9d9d9")
        self.user_label.configure(disabledforeground="#a3a3a3")
        self.user_label.configure(foreground="#000000")
        self.user_label.configure(text='''Label''')

        self.email_label = tk.Label(self.Frame2)
        self.email_label.place(relx=0.062, rely=0.256, height=51, width=424)
        self.email_label.configure(activebackground="#f9f9f9")
        self.email_label.configure(activeforeground="black")
        self.email_label.configure(background="#d9d9d9")
        self.email_label.configure(disabledforeground="#a3a3a3")
        self.email_label.configure(foreground="#000000")
        self.email_label.configure(highlightbackground="#d9d9d9")
        self.email_label.configure(highlightcolor="black")
        self.email_label.configure(text='''Label''')

        self.name_label = tk.Label(self.Frame2)
        self.name_label.place(relx=0.062, rely=0.466, height=51, width=424)
        self.name_label.configure(activebackground="#f9f9f9")
        self.name_label.configure(activeforeground="black")
        self.name_label.configure(background="#d9d9d9")
        self.name_label.configure(disabledforeground="#a3a3a3")
        self.name_label.configure(foreground="#000000")
        self.name_label.configure(highlightbackground="#d9d9d9")
        self.name_label.configure(highlightcolor="black")
        self.name_label.configure(text='''Label''')

        self.phone_label = tk.Label(self.Frame2)
        self.phone_label.place(relx=0.062, rely=0.662, height=52, width=424)
        self.phone_label.configure(activebackground="#f9f9f9")
        self.phone_label.configure(activeforeground="black")
        self.phone_label.configure(background="#d9d9d9")
        self.phone_label.configure(disabledforeground="#a3a3a3")
        self.phone_label.configure(foreground="#000000")
        self.phone_label.configure(highlightbackground="#d9d9d9")
        self.phone_label.configure(highlightcolor="black")
        self.phone_label.configure(text='''Label''')

        self.date_label = tk.Label(self.Frame2)
        self.date_label.place(relx=0.062, rely=0.827, height=51, width=424)
        self.date_label.configure(activebackground="#f9f9f9")
        self.date_label.configure(activeforeground="black")
        self.date_label.configure(background="#d9d9d9")
        self.date_label.configure(disabledforeground="#a3a3a3")
        self.date_label.configure(foreground="#000000")
        self.date_label.configure(highlightbackground="#d9d9d9")
        self.date_label.configure(highlightcolor="black")
        self.date_label.configure(text='''Label''')

        self.Label8 = tk.Label(self.Frame2)
        self.Label8.place(relx=0.329, rely=0.015, height=21, width=154)
        self.Label8.configure(background="#ffffff")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Username''')

        self.Label8_1 = tk.Label(self.Frame2)
        self.Label8_1.place(relx=0.329, rely=0.195, height=22, width=154)
        self.Label8_1.configure(activebackground="#f9f9f9")
        self.Label8_1.configure(activeforeground="black")
        self.Label8_1.configure(background="#ffffff")
        self.Label8_1.configure(disabledforeground="#a3a3a3")
        self.Label8_1.configure(foreground="#000000")
        self.Label8_1.configure(highlightbackground="#d9d9d9")
        self.Label8_1.configure(highlightcolor="black")
        self.Label8_1.configure(text='''Email Address''')

        self.Label8_2 = tk.Label(self.Frame2)
        self.Label8_2.place(relx=0.329, rely=0.406, height=21, width=154)
        self.Label8_2.configure(activebackground="#f9f9f9")
        self.Label8_2.configure(activeforeground="black")
        self.Label8_2.configure(background="#ffffff")
        self.Label8_2.configure(disabledforeground="#a3a3a3")
        self.Label8_2.configure(foreground="#000000")
        self.Label8_2.configure(highlightbackground="#d9d9d9")
        self.Label8_2.configure(highlightcolor="black")
        self.Label8_2.configure(text='''Full Name''')

        self.Label8_3 = tk.Label(self.Frame2)
        self.Label8_3.place(relx=0.337, rely=0.603, height=21, width=154)
        self.Label8_3.configure(activebackground="#f9f9f9")
        self.Label8_3.configure(activeforeground="black")
        self.Label8_3.configure(background="#ffffff")
        self.Label8_3.configure(disabledforeground="#a3a3a3")
        self.Label8_3.configure(foreground="#000000")
        self.Label8_3.configure(highlightbackground="#d9d9d9")
        self.Label8_3.configure(highlightcolor="black")
        self.Label8_3.configure(text='''Phone Number''')

        self.Label8_4 = tk.Label(self.Frame2)
        self.Label8_4.place(relx=0.349, rely=0.767, height=21, width=154)
        self.Label8_4.configure(activebackground="#f9f9f9")
        self.Label8_4.configure(activeforeground="black")
        self.Label8_4.configure(background="#ffffff")
        self.Label8_4.configure(disabledforeground="#a3a3a3")
        self.Label8_4.configure(foreground="#000000")
        self.Label8_4.configure(highlightbackground="#d9d9d9")
        self.Label8_4.configure(highlightcolor="black")
        self.Label8_4.configure(text='''Date Register''')

        self.log_out_btn = tk.Button(self.Frame2)
        self.log_out_btn.place(relx=0.349, rely=0.932, height=34, width=137)
        self.log_out_btn.configure(activebackground="#ececec")
        self.log_out_btn.configure(activeforeground="#000000")
        self.log_out_btn.configure(background="#ff0000")
        self.log_out_btn.configure(disabledforeground="#a3a3a3")
        self.log_out_btn.configure(foreground="#ffffff")
        self.log_out_btn.configure(highlightbackground="#d9d9d9")
        self.log_out_btn.configure(highlightcolor="black")
        self.log_out_btn.configure(pady="0")
        self.log_out_btn.configure(text='''Log Out''')

if __name__ == '__main__':
    vp_start_gui()





